# Generated by Django 4.2.26 on 2026-04-04 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Betreff')),
                ('body_html', models.TextField(verbose_name='Inhalt (HTML)')),
                ('body_text', models.TextField(blank=True, help_text='Wird automatisch aus HTML generiert, kann aber manuell angepasst werden.', verbose_name='Inhalt (Text)')),
                ('recipient_type', models.CharField(choices=[('all', 'Alle Benutzer'), ('members', 'Nur Mitglieder'), ('visitors', 'Nur Besucher'), ('guests', 'Nur Gaeste'), ('groups', 'Bestimmte Gruppen'), ('manual', 'Manuelle Auswahl')], default='members', max_length=20, verbose_name='Empfaenger-Typ')),
                ('recipient_groups', models.TextField(blank=True, help_text='Komma-getrennte LDAP-Gruppennamen (nur bei Typ "Bestimmte Gruppen")', verbose_name='Gruppen')),
                ('recipient_emails_manual', models.TextField(blank=True, help_text='Eine E-Mail-Adresse pro Zeile (nur bei Typ "Manuelle Auswahl")', verbose_name='Manuelle Empfaenger')),
                ('from_name', models.CharField(default='Beispielgemeinde', max_length=100, verbose_name='Absender-Name')),
                ('reply_to', models.EmailField(blank=True, max_length=254, verbose_name='Antwort-an')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('sending', 'Wird versendet'), ('sent', 'Versendet'), ('failed', 'Fehlgeschlagen')], default='draft', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Versendet am')),
                ('total_recipients', models.IntegerField(default=0, verbose_name='Empfaenger gesamt')),
                ('successful_count', models.IntegerField(default=0, verbose_name='Erfolgreich')),
                ('failed_count', models.IntegerField(default=0, verbose_name='Fehlgeschlagen')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mail_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
            ],
            options={
                'verbose_name': 'Mail-Kampagne',
                'verbose_name_plural': 'Mail-Kampagnen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('subject', models.CharField(max_length=255, verbose_name='Betreff')),
                ('body_html', models.TextField(verbose_name='Inhalt (HTML)')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
            ],
            options={
                'verbose_name': 'Mail-Vorlage',
                'verbose_name_plural': 'Mail-Vorlagen',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='Empfaenger')),
                ('recipient_name', models.CharField(blank=True, max_length=200, verbose_name='Name')),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('sent', 'Zugestellt'), ('failed', 'Fehlgeschlagen')], default='pending', max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, verbose_name='Fehlermeldung')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Gesendet am')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='mailing.mailcampaign', verbose_name='Kampagne')),
            ],
            options={
                'verbose_name': 'Mail-Protokoll',
                'verbose_name_plural': 'Mail-Protokolle',
                'ordering': ['-sent_at'],
            },
        ),
    ]
