# Generated by Django 4.2.26 on 2026-04-04 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailcampaign',
            name='recipient_type',
            field=models.CharField(choices=[('all', 'Alle Benutzer'), ('members', 'Mitglieder'), ('family', 'Angehoerige'), ('visitors', 'Besucher'), ('guests', 'Gaeste'), ('groups', 'Bestimmte Gruppen'), ('manual', 'Manuelle Auswahl')], default='members', max_length=20, verbose_name='Empfaenger-Typ'),
        ),
    ]
