# Generated by Django 4.2.26 on 2026-04-04 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_sysadmin_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailcampaign',
            name='footer_html',
            field=models.TextField(blank=True, default='<div style="text-align: center; padding: 15px; font-size: 12px; color: #666;"><p>Diese E-Mail wurde ueber ChurchAdmin versendet.</p><p>&copy; 2026 Beispielgemeinde</p></div>', verbose_name='Footer (HTML)'),
        ),
    ]
