# Generated by Django 4.2.26 on 2026-04-04 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_add_footer_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailcampaign',
            name='footer_html',
            field=models.TextField(blank=True, default='', verbose_name='Footer (HTML)'),
        ),
    ]
