# Generated by Django 4.2.26 on 2026-04-05 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0007_welcome_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailcampaign',
            name='from_name',
            field=models.CharField(default='Gemeinde', max_length=100, verbose_name='Absender-Name'),
        ),
    ]
