"""
Django settings for main project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import ldap

# .env laden (falls vorhanden)
_env_path = Path(__file__).resolve().parent.parent / '.env'
if _env_path.exists():
    with open(_env_path) as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith('#') and '=' in line:
                key, _, value = line.partition('=')
                os.environ.setdefault(key.strip(), value.strip())
from django_auth_ldap.config import LDAPSearch, GroupOfNamesType

# Admin Konfiguration
ADMIN_SITE_HEADER = "Church Administration"
ADMIN_SITE_TITLE = "ChurchAdmin"

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'change-me-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'wir.example-church.de']

# Trusted origins für CSRF und CORS
CSRF_TRUSTED_ORIGINS = [
    'https://verwaltung.example-church.de',
]

# CORS Einstellungen (falls du API-Endpoints hast)
CORS_ALLOWED_ORIGINS = [
    'https://verwaltung.example-church.de',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bootstrap5',
    'captcha',
    'authapp',
    'mailing',
    'privacy',
    'tickets',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'main.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
                BASE_DIR / 'templates',
                ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'authapp.context_processors.church_settings',
                'authapp.context_processors.user_permissions',
            ],
        },
    },
]

WSGI_APPLICATION = 'main.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = []


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'de-de'
TIME_ZONE = 'Europe/Berlin'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Zusätzliche Static files Verzeichnisse
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# STATIC_ROOT für Production (wo collectstatic die Dateien sammelt)
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Sicherstellen, dass Static Files gefunden werden
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# LDAP Konfiguration
# Grundlegende Verbindung zum LDAP-Server

# SSL-Zertifikat-Validierung deaktivieren (nur für Entwicklung!)
# Für Produktion sollte ein gültiges SSL-Zertifikat verwendet werden
ldap.set_option(ldap.OPT_X_TLS_REQUIRE_CERT, ldap.OPT_X_TLS_NEVER)

AUTH_LDAP_SERVER_URI = os.environ.get('LDAP_SERVER_URI', 'ldaps://ldap.example-church.de')
AUTH_LDAP_BIND_DN = os.environ.get('LDAP_BIND_DN', 'cn=admin,dc=example-church,dc=de')
AUTH_LDAP_BIND_PASSWORD = os.environ.get('LDAP_BIND_PASSWORD', '')

AUTH_LDAP_USER_SEARCH = LDAPSearch(
    "ou=Users,dc=example-church,dc=de",
    ldap.SCOPE_SUBTREE,
    "(|(cn=%(user)s)(uid=%(user)s)(mail=%(user)s))"
)

AUTH_LDAP_USER_ATTR_MAP = {
    "first_name": "givenName",
    "last_name": "sn",
    "email": "mail",
}

# Username wird aus cn geholt, aber nicht automatisch überschrieben
# Dies verhindert IntegrityErrors beim Login mit E-Mail
from django_auth_ldap.config import LDAPSearch
AUTH_LDAP_USER_DN_TEMPLATE = None  # Use search instead

# WICHTIG für SSO: User bei jedem Login aktualisieren
# Passwort wird NICHT in Django-DB gespeichert, immer gegen LDAP validiert
AUTH_LDAP_ALWAYS_UPDATE_USER = True
AUTH_LDAP_MIRROR_GROUPS = True

# User-Profil bei jedem Login aktualisieren
AUTH_LDAP_FIND_GROUP_PERMS = True

# Gruppen Suche
AUTH_LDAP_GROUP_SEARCH = LDAPSearch(
    "ou=Groups,dc=example-church,dc=de",
    ldap.SCOPE_SUBTREE,
    "(objectClass=groupOfNames)"
)

AUTH_LDAP_GROUP_TYPE = GroupOfNamesType()

# Benutzer Flags basierend auf Gruppen
# WICHTIG: is_active NICHT gesetzt - alle LDAP-Benutzer sind standardmäßig aktiv
AUTH_LDAP_USER_FLAGS_BY_GROUP = {
    "is_staff": "cn=Mitglieder,ou=Groups,dc=example-church,dc=de",
    "is_superuser": "cn=Technik und Infrastruktur,cn=Mitarbeiter,cn=Mitglieder,ou=Groups,dc=example-church,dc=de",
}

# Gruppen Berechtigungen
AUTH_LDAP_FIND_GROUP_PERMS = True

# Cache Settings
AUTH_LDAP_CACHE_TIMEOUT = 3600

# LDAP Einstellungen
# Benutzer bei jedem Login mit LDAP-Daten synchronisieren
AUTH_LDAP_ALWAYS_UPDATE_USER = True
# Gruppen-Mitgliedschaften synchronisieren
AUTH_LDAP_MIRROR_GROUPS = True

AUTHENTICATION_BACKENDS = [
    'django_auth_ldap.backend.LDAPBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# CAPTCHA Einstellungen
CAPTCHA_LENGTH = 6
CAPTCHA_FONT_SIZE = 28
CAPTCHA_IMAGE_SIZE = (160, 50)
CAPTCHA_LETTER_ROTATION = (-20, 20)

EMAIL_HOST = 'example-church.de'  # für Postfix
EMAIL_PORT = 25  # Standard SMTP Port
DEFAULT_FROM_EMAIL = 'webmaster@example-church.de'
SERVER_EMAIL = 'webmaster@example-church.de'

