# Generated by Django 4.2.26 on 2026-04-04 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, verbose_name='Version')),
                ('title', models.CharField(default='Datenschutzerklaerung der Beispielgemeinde', max_length=200, verbose_name='Titel')),
                ('content_html', models.TextField(verbose_name='Inhalt (HTML)')),
                ('is_active', models.BooleanField(default=False, help_text='Nur eine Version kann aktiv sein', verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
            ],
            options={
                'verbose_name': 'Datenschutzerklaerung',
                'verbose_name_plural': 'Datenschutzerklaerungen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='Benutzername')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('reason', models.TextField(blank=True, verbose_name='Begruendung')),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('approved', 'Genehmigt'), ('completed', 'Abgeschlossen'), ('rejected', 'Abgelehnt')], default='pending', max_length=20, verbose_name='Status')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Bearbeitet am')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_deletions', to=settings.AUTH_USER_MODEL, verbose_name='Bearbeitet von')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletion_requests', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Loeschantrag',
                'verbose_name_plural': 'Loeschantraege',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type', models.CharField(choices=[('privacy_policy', 'Datenschutzerklaerung'), ('data_processing', 'Datenverarbeitung'), ('email_communication', 'E-Mail-Kommunikation')], max_length=50, verbose_name='Art der Einwilligung')),
                ('policy_version', models.CharField(blank=True, max_length=20, verbose_name='Version')),
                ('granted', models.BooleanField(default=True, verbose_name='Erteilt')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-Adresse')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Zeitpunkt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Einwilligung',
                'verbose_name_plural': 'Einwilligungen',
                'ordering': ['-timestamp'],
            },
        ),
    ]
