# Generated by Django 4.2.26 on 2026-04-04 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('impressum', 'Impressum'), ('nutzungsbedingungen', 'Nutzungsbedingungen')], max_length=50, unique=True, verbose_name='Seitentyp')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('content_html', models.TextField(verbose_name='Inhalt (HTML)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
            ],
            options={
                'verbose_name': 'Rechtliche Seite',
                'verbose_name_plural': 'Rechtliche Seiten',
            },
        ),
    ]
