# Generated by Django 4.2.26 on 2026-04-04 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacy', '0003_default_impressum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentlog',
            name='consent_type',
            field=models.CharField(choices=[('privacy_policy', 'Datenschutzerklaerung'), ('data_processing', 'Datenverarbeitung'), ('email_communication', 'E-Mail-Kommunikation'), ('member_list', 'Gemeindeliste (Name, Kontaktdaten sichtbar fuer Mitglieder)')], max_length=50, verbose_name='Art der Einwilligung'),
        ),
    ]
