# Generated by Django 4.2.26 on 2026-04-04 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacy', '0004_add_member_list_consent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalpage',
            name='page_type',
            field=models.CharField(choices=[('impressum', 'Impressum'), ('nutzungsbedingungen', 'Nutzungsbedingungen'), ('cookies', 'Cookie-Richtlinie')], max_length=50, unique=True, verbose_name='Seitentyp'),
        ),
    ]
