# Generated by Django 4.2.26 on 2026-04-05 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacy', '0005_add_cookies_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacypolicy',
            name='title',
            field=models.CharField(default='Datenschutzerklaerung', max_length=200, verbose_name='Titel'),
        ),
    ]
