# Generated by Django 4.2.26 on 2026-05-17 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_cn', models.CharField(db_index=True, help_text='Benutzer, ueber den die Notiz geht', max_length=120, verbose_name='Betroffener (LDAP-cn)')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('_content_ciphertext', models.TextField(db_column='content_ciphertext', verbose_name='Inhalt (verschluesselt)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_notes', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Seelsorge-Notiz',
                'verbose_name_plural': 'Seelsorge-Notizen',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonNoteAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_target_cn', models.CharField(db_index=True, help_text='Wird redundant gespeichert, damit Audit nach Loeschen erhalten bleibt', max_length=120)),
                ('note_title', models.CharField(blank=True, max_length=200)),
                ('action', models.CharField(choices=[('view', 'Angesehen'), ('create', 'Erstellt'), ('update', 'Bearbeitet'), ('delete', 'Geloescht')], max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('note', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_log', to='personnotes.personnote')),
                ('viewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='note_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Zugriffs-Eintrag',
                'verbose_name_plural': 'Zugriffs-Eintraege',
                'ordering': ['-timestamp'],
            },
        ),
    ]
