# Generated by Django 5.2.8 on 2025-11-30 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LDAPConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('server_uri', models.CharField(max_length=200)),
                ('bind_dn', models.CharField(max_length=200)),
                ('bind_password', models.CharField(blank=True, max_length=200)),
                ('user_search_base', models.CharField(max_length=200)),
                ('user_search_filter', models.CharField(default='(uid=%(user)s)', max_length=200)),
                ('group_search_base', models.CharField(blank=True, max_length=200)),
                ('attribute_mapping', models.TextField(default='{"first_name": "givenName", "last_name": "sn", "email": "mail"}')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LDAP Konfiguration',
                'verbose_name_plural': 'LDAP Konfigurationen',
            },
        ),
        migrations.CreateModel(
            name='LDAPUserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('details', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LDAP Log',
                'verbose_name_plural': 'LDAP Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
