# Generated by Django 4.2.26 on 2026-02-01 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('email', 'E-Mail'), ('recaptcha', 'reCAPTCHA'), ('ldap', 'LDAP'), ('registration', 'Registrierung'), ('general', 'Allgemein')], default='general', max_length=50)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField(blank=True)),
                ('description', models.TextField(blank=True, help_text='Beschreibung der Einstellung')),
                ('is_encrypted', models.BooleanField(default=False, help_text='Wert verschlüsselt speichern (z.B. Passwörter)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Anwendungseinstellung',
                'verbose_name_plural': 'Anwendungseinstellungen',
                'ordering': ['category', 'key'],
            },
        ),
    ]
