# Generated by Django 4.2.26 on 2026-02-01 00:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authapp', '0002_appsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_ldap_cn', models.CharField(help_text='LDAP CN des Betroffenen', max_length=200)),
                ('subject_name', models.CharField(help_text='Name des Betroffenen', max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('in_progress', 'In Bearbeitung'), ('on_hold', 'Pausiert'), ('completed', 'Abgeschlossen'), ('cancelled', 'Abgebrochen')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_processes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prozess-Instanz',
                'verbose_name_plural': 'Prozess-Instanzen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0, help_text='Reihenfolge (unterstützt Drag & Drop)')),
                ('default_assignee', models.CharField(choices=[('pastor', 'Pastor'), ('admin', 'Administrator'), ('mentor', 'Mentor'), ('auto', 'Automatisch')], default='admin', max_length=50)),
                ('is_required', models.BooleanField(default=True)),
                ('estimated_days', models.IntegerField(default=1, help_text='Geschätzte Dauer in Tagen')),
            ],
            options={
                'verbose_name': 'Prozess-Schritt',
                'verbose_name_plural': 'Prozess-Schritte',
                'ordering': ['template', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ProcessTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('process_type', models.CharField(choices=[('member_onboarding', 'Mitglieder-Onboarding'), ('family_onboarding', 'Familien-Onboarding'), ('volunteer_onboarding', 'Mitarbeiter-Onboarding'), ('offboarding', 'Offboarding'), ('custom', 'Benutzerdefiniert')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auto_email_enabled', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prozess-Template',
                'verbose_name_plural': 'Prozess-Templates',
                'ordering': ['process_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProcessStepInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('in_progress', 'In Bearbeitung'), ('completed', 'Abgeschlossen'), ('skipped', 'Übersprungen')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_steps', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_steps', to=settings.AUTH_USER_MODEL)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_instances', to='authapp.processinstance')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authapp.processstep')),
            ],
            options={
                'verbose_name': 'Schritt-Instanz',
                'verbose_name_plural': 'Schritt-Instanzen',
                'ordering': ['process', 'step__order'],
            },
        ),
        migrations.AddField(
            model_name='processstep',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='authapp.processtemplate'),
        ),
        migrations.CreateModel(
            name='ProcessNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('process_started', 'Prozess gestartet'), ('process_completed', 'Prozess abgeschlossen'), ('step_assigned', 'Schritt zugewiesen'), ('step_completed', 'Schritt abgeschlossen'), ('step_overdue', 'Schritt überfällig')], max_length=50)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='authapp.processinstance')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prozess-Benachrichtigung',
                'verbose_name_plural': 'Prozess-Benachrichtigungen',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddField(
            model_name='processinstance',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authapp.processtemplate'),
        ),
        migrations.CreateModel(
            name='ProcessChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('step_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='authapp.processstepinstance')),
            ],
            options={
                'verbose_name': 'Checklisten-Item',
                'verbose_name_plural': 'Checklisten-Items',
                'ordering': ['step_instance', 'order'],
            },
        ),
    ]
