# Generated by Django 4.2.26 on 2026-02-01 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authapp', '0003_processinstance_processstep_processtemplate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberListExportSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name der Export-Konfiguration', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('include_name', models.BooleanField(default=True, help_text='Vor- und Nachname')),
                ('include_email', models.BooleanField(default=True, help_text='E-Mail-Adresse')),
                ('include_phone', models.BooleanField(default=False, help_text='Telefonnummer')),
                ('include_address', models.BooleanField(default=False, help_text='Adresse')),
                ('include_birthday', models.BooleanField(default=False, help_text='Geburtsdatum')),
                ('include_groups', models.BooleanField(default=True, help_text='Gruppenmitgliedschaften')),
                ('include_family', models.BooleanField(default=True, help_text='Familienzugehörigkeit')),
                ('user_filter', models.CharField(choices=[('all', 'Alle Benutzer'), ('members', 'Nur Mitglieder'), ('visitors', 'Nur Besucher'), ('family_heads', 'Nur Familienoberhäupter')], default='all', max_length=50)),
                ('sort_by', models.CharField(choices=[('sn', 'Nach Nachname'), ('givenName', 'Nach Vorname'), ('mail', 'Nach E-Mail')], default='sn', max_length=50)),
                ('is_public', models.BooleanField(default=True, help_text='Für alle Benutzer verfügbar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_export_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Export-Einstellung',
                'verbose_name_plural': 'Export-Einstellungen',
                'ordering': ['name'],
            },
        ),
    ]
