# Generated by Django 4.2.26 on 2026-02-01 01:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authapp', '0004_memberlistexportsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('manage_users', 'Benutzer verwalten'), ('manage_groups', 'Gruppen verwalten'), ('manage_families', 'Familien verwalten'), ('manage_mail', 'Mail-Verwaltung'), ('view_members', 'Gemeindeliste ansehen'), ('edit_members', 'Gemeindeliste bearbeiten'), ('export_members', 'Gemeindeliste exportieren')], help_text='Die Berechtigung, die zugewiesen wird', max_length=50)),
                ('group_name', models.CharField(help_text="Name der LDAP-Gruppe (z.B. 'Leitung', 'Pastor')", max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Ist diese Zuordnung aktiv?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Berechtigungs-Zuordnung',
                'verbose_name_plural': 'Berechtigungs-Zuordnungen',
                'ordering': ['permission', 'group_name'],
                'indexes': [models.Index(fields=['permission', 'is_active'], name='authapp_per_permiss_47103f_idx'), models.Index(fields=['group_name', 'is_active'], name='authapp_per_group_n_e3e829_idx')],
                'unique_together': {('permission', 'group_name')},
            },
        ),
    ]
