# Generated by Django 4.2.26 on 2026-02-01 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_permissionmapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionmapping',
            name='permission',
            field=models.CharField(choices=[('manage_users', 'Benutzer verwalten'), ('manage_groups', 'Gruppen verwalten'), ('manage_families', 'Familien verwalten'), ('manage_mail', 'Mail-Verwaltung'), ('manage_mail_domains', 'Mail-Domains verwalten'), ('view_members', 'Gemeindeliste ansehen'), ('edit_members', 'Gemeindeliste bearbeiten'), ('export_members', 'Gemeindeliste exportieren')], help_text='Die Berechtigung, die zugewiesen wird', max_length=50),
        ),
    ]
