# Generated by Django 4.2.26 on 2026-02-01 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authapp', '0006_alter_permissionmapping_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='Kryptographisch sicherer Token', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Ablaufzeitpunkt des Tokens (24 Stunden)')),
                ('used', models.BooleanField(default=False, help_text='Wurde der Token bereits verwendet?')),
                ('used_at', models.DateTimeField(blank=True, help_text='Zeitpunkt der Verwendung', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP-Adresse der Anfrage', null=True)),
                ('user', models.ForeignKey(help_text='Der Benutzer für den dieser Token gilt', on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Passwort-Reset-Token',
                'verbose_name_plural': 'Passwort-Reset-Tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token', 'used'], name='authapp_pas_token_6d1f87_idx'), models.Index(fields=['user', 'created_at'], name='authapp_pas_user_id_d03d4c_idx')],
            },
        ),
    ]
