# Generated by Django 4.2.26 on 2026-02-01 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Interner Name der Vorlage', max_length=200, verbose_name='Vorlagenname')),
                ('template_type', models.CharField(choices=[('member_welcome', 'Begrüßung neues Mitglied'), ('member_removed', 'Mitgliedschaft beendet'), ('password_reset', 'Passwort zurücksetzen'), ('account_created', 'Konto erstellt'), ('custom', 'Benutzerdefiniert')], help_text='Typ der E-Mail-Vorlage', max_length=50, unique=True, verbose_name='Vorlagentyp')),
                ('subject', models.CharField(help_text='Betreff der E-Mail. Platzhalter: {{name}}, {{email}}, {{username}}', max_length=200, verbose_name='Betreff')),
                ('body', models.TextField(help_text='Nachrichtentext. Platzhalter: {{name}}, {{email}}, {{username}}, {{first_name}}, {{last_name}}', verbose_name='Nachricht')),
                ('is_active', models.BooleanField(default=True, help_text='Wenn deaktiviert, wird die E-Mail nicht versendet', verbose_name='Aktiv')),
                ('send_automatically', models.BooleanField(default=True, help_text='E-Mail automatisch beim Ereignis versenden', verbose_name='Automatisch senden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
            ],
            options={
                'verbose_name': 'E-Mail-Vorlage',
                'verbose_name_plural': 'E-Mail-Vorlagen',
                'ordering': ['template_type', 'name'],
            },
        ),
    ]
