# Generated by Django 4.2.26 on 2026-02-01 04:17

from django.db import migrations


def remove_duplicate_emails(apps, schema_editor):
    """Remove duplicate email addresses, keeping only the oldest user with each email"""
    from django.contrib.auth.models import User
    from django.db.models import Count, Min

    # Find all duplicate emails
    duplicates = User.objects.values('email').annotate(
        count=Count('id'),
        min_id=Min('id')
    ).filter(count__gt=1, email__isnull=False).exclude(email='')

    # Delete all but the oldest user for each duplicate email
    for dup in duplicates:
        User.objects.filter(email=dup['email']).exclude(id=dup['min_id']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_emailtemplate'),
    ]

    operations = [
        # First, remove any duplicate emails
        migrations.RunPython(remove_duplicate_emails, reverse_code=migrations.RunPython.noop),

        # Add unique constraint to email field using raw SQL
        # (since we can't use AlterField on django.contrib.auth.User)
        migrations.RunSQL(
            sql=[
                # Create unique index on email field (ignoring empty strings)
                "CREATE UNIQUE INDEX auth_user_email_unique ON auth_user(email) WHERE email != '';",
            ],
            reverse_sql=[
                "DROP INDEX IF EXISTS auth_user_email_unique;",
            ],
        ),
    ]
