# Generated by Django 4.2.26 on 2026-02-01 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authapp', '0009_make_email_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='LDAPBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_type', models.CharField(choices=[('full', 'Vollständig'), ('users', 'Nur Benutzer'), ('groups', 'Nur Gruppen'), ('domains', 'Nur Mail-Domains')], default='full', max_length=20, verbose_name='Backup-Typ')),
                ('status', models.CharField(choices=[('running', 'Läuft'), ('completed', 'Erfolgreich'), ('failed', 'Fehlgeschlagen')], default='running', max_length=20, verbose_name='Status')),
                ('filename', models.CharField(help_text='LDIF-Dateiname', max_length=255, verbose_name='Dateiname')),
                ('file_path', models.CharField(help_text='Vollständiger Pfad zur Backup-Datei', max_length=500, verbose_name='Dateipfad')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='Dateigröße (Bytes)')),
                ('entry_count', models.IntegerField(default=0, help_text='Anzahl exportierter LDAP-Einträge', verbose_name='Anzahl Einträge')),
                ('user_count', models.IntegerField(default=0, verbose_name='Anzahl Benutzer')),
                ('group_count', models.IntegerField(default=0, verbose_name='Anzahl Gruppen')),
                ('domain_count', models.IntegerField(default=0, verbose_name='Anzahl Mail-Domains')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Abgeschlossen am')),
                ('error_message', models.TextField(blank=True, verbose_name='Fehlermeldung')),
                ('notes', models.TextField(blank=True, help_text='Optionale Notizen zum Backup', verbose_name='Notizen')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
            ],
            options={
                'verbose_name': 'LDAP Backup',
                'verbose_name_plural': 'LDAP Backups',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='authapp_lda_created_2ef452_idx'), models.Index(fields=['status'], name='authapp_lda_status_46ffd2_idx'), models.Index(fields=['backup_type'], name='authapp_lda_backup__dc5f4d_idx')],
            },
        ),
    ]
