# Generated by Django 4.2.26 on 2026-04-04 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authapp', '0010_ldapbackup'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nachname')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail-Adresse')),
                ('reason', models.TextField(help_text='Warum moechten Sie sich registrieren? Wie haben Sie zur Gemeinde gefunden?', verbose_name='Begruendung')),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('approved', 'Genehmigt'), ('rejected', 'Abgelehnt')], default='pending', max_length=20, verbose_name='Status')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Geprueft am')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Ablehnungsgrund')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP-Adresse')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_registrations', to=settings.AUTH_USER_MODEL, verbose_name='Geprueft von')),
            ],
            options={
                'verbose_name': 'Registrierungsanfrage',
                'verbose_name_plural': 'Registrierungsanfragen',
                'ordering': ['-created_at'],
            },
        ),
    ]
