# Generated by Django 4.2.26 on 2026-04-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0011_registrationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationrequest',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='E-Mail bestaetigt'),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='verification_token',
            field=models.CharField(blank=True, max_length=64, verbose_name='Bestaetigungstoken'),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='status',
            field=models.CharField(choices=[('unverified', 'E-Mail nicht bestaetigt'), ('pending', 'Ausstehend'), ('approved', 'Genehmigt'), ('rejected', 'Abgelehnt')], default='unverified', max_length=20, verbose_name='Status'),
        ),
    ]
