# Generated by Django 4.2.26 on 2026-05-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0014_add_send_massmail_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='WiFiNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Interner Name (z.B. 'Gemeinde-WLAN')", max_length=100, verbose_name='Bezeichnung')),
                ('ssid', models.CharField(help_text='WLAN-Netzwerkname', max_length=100, verbose_name='SSID')),
                ('password', models.CharField(blank=True, help_text='WLAN-Passwort (PSK)', max_length=200, verbose_name='Passwort')),
                ('encryption_type', models.CharField(choices=[('WPA2', 'WPA2/PSK'), ('WPA3', 'WPA3/SAE'), ('WEP', 'WEP'), ('None', 'Offen (kein Passwort)')], default='WPA2', max_length=10, verbose_name='Verschlüsselung')),
                ('is_hidden', models.BooleanField(default=False, help_text='SSID wird nicht gesendet', verbose_name='Verstecktes Netzwerk')),
                ('is_active', models.BooleanField(default=True, help_text='Wird in der Geräte-Konfiguration angeboten', verbose_name='Aktiv')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Reihenfolge')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WiFi-Netzwerk',
                'verbose_name_plural': 'WiFi-Netzwerke',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='category',
            field=models.CharField(choices=[('email', 'E-Mail'), ('recaptcha', 'reCAPTCHA'), ('ldap', 'LDAP'), ('registration', 'Registrierung'), ('general', 'Allgemein'), ('autoconfig', 'Geräte-Konfiguration')], default='general', max_length=50),
        ),
    ]
