# Generated by Django 4.2.26 on 2026-05-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0015_wifinetwork_alter_appsettings_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationResponseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('approve_default', 'Standardtext: Genehmigung'), ('reject_default', 'Standardtext: Ablehnung'), ('snippet', 'Textbaustein (Checkbox)')], max_length=20, verbose_name='Typ')),
                ('name', models.CharField(help_text='Wird als Checkbox-Label oder interner Name angezeigt', max_length=200, verbose_name='Bezeichnung')),
                ('text', models.TextField(help_text='Platzhalter: {{vorname}}, {{nachname}}, {{email}}, {{gemeinde}}', verbose_name='Text')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Reihenfolge')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Registrierungs-Antwortvorlage',
                'verbose_name_plural': 'Registrierungs-Antwortvorlagen',
                'ordering': ['template_type', 'sort_order', 'name'],
            },
        ),
    ]
