# Generated by Django 4.2.26 on 2026-05-24 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0016_registrationresponsetemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionmapping',
            name='permission',
            field=models.CharField(choices=[('manage_users', 'Benutzer verwalten'), ('manage_groups', 'Gruppen verwalten'), ('manage_families', 'Familien verwalten'), ('manage_mail', 'Mail-Verwaltung'), ('manage_mail_domains', 'Mail-Domains verwalten'), ('send_massmail', 'Massen-E-Mail versenden'), ('manage_registrations', 'Registrierungsanfragen bearbeiten'), ('view_members', 'Gemeindeliste ansehen'), ('edit_members', 'Gemeindeliste bearbeiten'), ('export_members', 'Gemeindeliste exportieren'), ('manage_notes', 'Seelsorge-Notizen verwalten')], help_text='Die Berechtigung, die zugewiesen wird', max_length=50),
        ),
    ]
