# Generated by Django 4.2.26 on 2026-05-17 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelpArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='URL-Pfad, z.B. "mail-routing"', max_length=120, unique=True)),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('category', models.CharField(choices=[('general', 'Allgemein'), ('mail', 'E-Mail'), ('account', 'Konto & Profil'), ('devices', 'Geraete-Einrichtung'), ('privacy', 'Datenschutz'), ('admin', 'Administration')], default='general', max_length=20, verbose_name='Kategorie')),
                ('summary', models.CharField(blank=True, help_text='Wird in der Index-Liste angezeigt', max_length=300, verbose_name='Kurzfassung')),
                ('content_html', models.TextField(verbose_name='Inhalt (HTML)')),
                ('order', models.IntegerField(default=0, verbose_name='Reihenfolge')),
                ('is_published', models.BooleanField(default=True, verbose_name='Veroeffentlicht')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hilfe-Artikel',
                'verbose_name_plural': 'Hilfe-Artikel',
                'ordering': ['category', 'order', 'title'],
            },
        ),
    ]
